### ISSUE TITLE
GNPS2 and Sirius

### ISSUE THREAD

**Issue by AndreaCa96** [Zquinlan/ecoNet#10]
Hi Zack,
Do you think it will be possible to integrate Concise Workflow with the GNPS2 platform?
I tried to launch FBMN on the GNPS2 platform, and now I have an ID for my MN, but the cluster info summary is different.
[Uploading GNPS2 29 luglio.zip…]()

**Comment by AndreaCa96** [comment]
Thanks a lot!

**Comment by Zquinlan** [comment]
Yes, definitely! I am in the field for the next two weeks so progress on ConCISE might be a bit slow during that time. Do you want to send me the new cluster info summary sheet?

**Comment by AndreaCa96** [comment]
Hi Zack, I'm not sure which is the correct cluster info summary sheet. I have an nf_output directory with different files inside. I think the cluster info summary sheet could be this one
[clustersummary_with_network.zip](https://github.com/user-attachments/files/16425215/clustersummary_with_network.zip)

**Comment by AndreaCa96** [comment]
But here it is all the nf_output, and this is the task ID 8b5efe7f14eb42b3890c17dbbb1f8d21
[Uploading nf_output.zip…]()

**Comment by AndreaCa96** [comment]
[Uploading nf_output.zip…]()
[Uploading clustersummary_with_network.zip…]()

**Comment by AndreaCa96** [comment]
This is the task id 8b5efe7f14eb42b3890c17dbbb1f8d21 and this is the nf_output complete: 
[Uploading nf_output.zip…]()

**Comment by AndreaCa96** [comment]
This is the task id 8b5efe7f14eb42b3890c17dbbb1f8d21 and this is the nf_output complete:
[nf_output.zip](https://github.com/user-attachments/files/16425628/nf_output.zip)

**Comment by Zquinlan** [comment]
I took a look today. The file you want is the "clustersummary_with_network.tsv" in the "networking" subdirectory. It should still work in conCISE because they haven't changed the feature number and subnetwork column names. However, I have not integrated a way to manually supply the library match information directly into ConCISE so currently it cannot work with GNPS 2. I hope to have those changes added by the end of the week and will update this thread when that is done!

**Comment by Zquinlan** [comment]
Hi! I have updated ConCISE so now you can use your own spectral library match file. In place of supplying the GNPS task id, supply your spectral library match file from GNPS 2. In GNPS 1 this file was called DBResults. If you are using the GUI on windows you can download the new version [here](https://github.com/Zquinlan/conCISE/releases/download/v1.30/conCISEGui.exe). The Binder and CLI are also up to date. Let me know if you run into any issues with this and I will do my best to fix them swiftly!

**Comment by AndreaCa96** [comment]
Hi Zach I have tried to run ConCISE with GNPS2 but there is this error, I have put the file in libraries with name "merged_results_with_gnps.tsv" and the same canopus file with the file "clustersummary_with_network.tsv" 
Exception in thread Thread-1 (runWorkFlow):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "workflowMain.py", line 100, in runWorkFlow
  File "pandas\core\frame.py", line 4108, in __getitem__
  File "pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
  File "pandas\core\indexes\base.py", line 6252, in _raise_if_missing
KeyError: "['network'] not in index"

I have tried also to run with some old GNPS1 and it seems that doesn't work but I think that there is a problem with server of GNPS.

Thank you in advance!

**Comment by AndreaCa96** [comment]
Now with GNPS1 it work but i have always the same problem with the work from GNPS2. I can sand you all the files if it's necessary! Thank you again !

**Comment by Zquinlan** [comment]
They changed the name of the network column name. I updated the code with a catch-case and it should now be available to you.

**Comment by AndreaCa96** [comment]
I have tried to download the last version 11 hours ago and I try to run the ConCISE workflow and I have always the same error concerning the network column name 
Exception in thread Thread-1 (runWorkFlow):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "workflowMain.py", line 105, in runWorkFlow
  File "pandas\core\frame.py", line 4108, in __getitem__
  File "pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
  File "pandas\core\indexes\base.py", line 6252, in _raise_if_missing
KeyError: "['network'] not in index"

**Comment by Zquinlan** [comment]
Ahhh! Sorry, I went through and found the typo. Try it now :)

**Comment by AndreaCa96** [comment]
Exception in thread Thread-1 (runWorkFlow):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "workflowMain.py", line 105, in runWorkFlow
  File "pandas\core\frame.py", line 4108, in __getitem__
  File "pandas\core\indexes\base.py", line 6200, in _get_indexer_strict
  File "pandas\core\indexes\base.py", line 6252, in _raise_if_missing
KeyError: "['network'] not in index" always the same error

**Comment by AndreaCa96** [comment]
Here it is all the files from GNPS2 + canopus compound summary
[GNPS2 + Canopus.zip](https://github.com/user-attachments/files/16806130/GNPS2.%2B.Canopus.zip)

**Comment by AndreaCa96** [comment]
From this zip I have put in the GNPS task ID the file inside the nf_output, in library with the name "merged_results_with_gnps.tsv" and for the network file the file with the name "clustersummary_with_network.tsv" for canopus the file "canopus_compound_summary.tsv"

**Comment by Zquinlan** [comment]
Hi!

Sorry it keeps not working. Having your files helped immensely. I fixed the bug and am updating the github now. Below are attached the ConCISE consensus files for both classyFire and NPClassyfire! :)

Classyfire:
10 out of 10 (100.0%) networks with Library ID's found a consensus annotation
41 out of 100 (41.0%) networks with Insilico annotations found a consensus annotation
46.37% of all networks with an annotation recieved a consensus annotation

NPClassyfire:
8 out of 8 (100.0%) networks with Library ID's found a consensus annotation
53 out of 102 (51.970000000000006%) networks with Insilico annotations found a consensus annotation
55.46% of all networks with an annotation recieved a consensus annotation


[conciseConsensus.zip](https://github.com/user-attachments/files/16808509/conciseConsensus.zip)
