### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by duanlaoyao** [Zquinlan/ecoNet#4]
Is there a detailed illustrated tutorial on how to use conCISEGui?

**Comment by Zquinlan** [comment]
Hi,

I just updated the github pages with a short tutorial on how to use the GUI (https://zquinlan.github.io/conCISE/). Over the next few days I will add more information and detail but wanted to get something with a bit more clear instructions that what is available from our manuscript available to you ASAP.

-zaq

**Comment by duanlaoyao** [comment]
Thanks

**Comment by duanlaoyao** [comment]
I'm sorry that due to my limited programming skills, I still failed to run the software according to the case file you published. Looking forward to the release of the detailed operation process, thank you again for your reply. I wish you all the best in your work and life

**Comment by Zquinlan** [comment]
The tutorial for the GUI is already up on https://zquinlan.github.io/conCISE/_pages/Tutorial/index.html

However I am happy to answer more specific questions if there is something which is not working for you?

**Comment by duanlaoyao** [comment]
Thank you very much for your reply. According to your operation process, the final file still cannot be generated, is my computer not suitable? The bottom image is my operation interface. Thank you for your kind reply and help!

![image](https://github.com/Zquinlan/conCISE/assets/146741565/9f62c47c-c8a4-4680-8bef-6ec120000a1a)
![image](https://github.com/Zquinlan/conCISE/assets/146741565/be1c19d2-c09c-48ce-9ca9-837163970ef2)

**Comment by duanlaoyao** [comment]
Thank you for your reply, the conCISE has been conCISE, and thank you for your concise help and reply！

**Comment by duanlaoyao** [comment]
Thank you for developing the software, which provides convenience for us to solve the experimental problems. However, we still have a problem when using the software, how to import CSV files into cytoscape for visualization?Looking forward to your reply！

**Comment by Zquinlan** [comment]
If you use the "import file from file" button in cytoscape it should allow you to import the ConciseConsensus.csv file.  This is their advice from the website: "Via the File menu: Load the galExpData.csv file under File menu, select Import → Table from File....
Drag and drop: Drag and drop the galExpData.csv file onto the Node Table.
The default settings are usually correct, although you may need to change the Key column to indicate which column will be used to match with the network key column."

https://cytoscape.org/cytoscape-tutorials/protocols/importing-data-from-tables/#/4

If something else is not working or erroring out, I'll be happy to help.

**Comment by duanlaoyao** [comment]
Thank you very much for your reply. Thank you very much for your unselfish help！
