### ISSUE TITLE
Ask questions

### ISSUE THREAD

**Issue by duanlaoyao** [Zquinlan/ecoNet#5]
How do I run the CANOPUS software?Shows that the website is not connected, do I need an additional plugin?Looking forward to your reply!
![image](https://github.com/Zquinlan/conCISE/assets/146741565/16e987d1-48c1-4e10-b043-bf2abb752543)

**Comment by Zquinlan** [comment]
This is a somewhat common issue I have run into while running the SIRIUS GUE. Typically, it still runs successfully and the loss of connection is only temporary. However, I have never gotten a clear answer if that assumption is true or if when this disconnect happens we are also losing some features. It would probably be worth scouting through the issues raised on the SIRIUS github issues page and asking the question directly to that team if they have not already answered it. https://github.com/boecker-lab/sirius

**Comment by duanlaoyao** [comment]
Thank you for your reply. I hope everything goes well with you！
